import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Wed-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased min-h-screen flex flex-col justify-between`}
      >
        <StoreProvider>
          <main className="">{children}</main>
          <Toaster></Toaster>
        </StoreProvider>
      </body>
    </html>
  );
}
